import Aoc2022

def main : IO Unit := do
  IO.println "Day1:"
  IO.println s!"Part 1: {← Day1.first_part}"
  IO.println s!"Part 2: {← Day1.second_part}"
  IO.println ""
  IO.println "Day2:"
  IO.println s!"Part 1: {← Day2.first_part}"
  IO.println s!"Part 2: {← Day2.second_part}"
  IO.println ""
  IO.println "Day3:"
  IO.println s!"Part 1: {← Day3.first_part}"
  IO.println s!"Part 2: {← Day3.second_part}"
  IO.println ""
  IO.println "Day4:"
  IO.println s!"Part 1: {← Day4.first_part}"
  IO.println s!"Part 2: {← Day4.second_part}"
  IO.println ""
  IO.println "Day5:"
  IO.println s!"Part 1: {← Day5.first_part}"
  IO.println s!"Part 2: {← Day5.second_part}"
  IO.println ""
  IO.println "Day6:"
  IO.println s!"Part 1: {← Day6.part 3}"
  IO.println s!"Part 2: {← Day6.part 13}"
  IO.println ""
  IO.println "Day7:"
  IO.println s!"Part 1: {← Day7.first_part}"
  IO.println s!"Part 2: {← Day7.second_part}"
  IO.println ""
  IO.println "Day8:"
--  IO.println s!"Part 1: {← Day8.first_part}" -- this is a bit slow
--  IO.println s!"Part 2: {← Day8.second_part}" -- this is a bit slow
  IO.println ""
  IO.println "Day9:"
  IO.println s!"Part 1: {← Day9.part 2}"
  IO.println s!"Part 2: {← Day9.part 10}"
  IO.println ""
  IO.println "Day10:"
  IO.println s!"Part 1: {← Day10.first_part}"
  IO.println s!"Part 2:\n{← Day10.second_part}"
  IO.println ""
