import Aoc2022

def main : IO Unit := do
  IO.println "Day1:"
  IO.println s!"Part 1: {← Day1.first_part}"
  IO.println s!"Part 2: {← Day1.second_part}"
  IO.println ""
  IO.println "Day2:"
  IO.println s!"Part 1: {← Day2.first_part}"
  IO.println s!"Part 2: {← Day2.second_part}"
  IO.println ""
  IO.println "Day3:"
  IO.println s!"Part 1: {← Day3.first_part}"
  IO.println s!"Part 2: {← Day3.second_part}"
  IO.println ""
  IO.println "Day4:"
  IO.println s!"Part 1: {← Day4.first_part}"
  IO.println s!"Part 2: {← Day4.second_part}"
  IO.println ""
  IO.println "Day5:"
  IO.println s!"Part 1: {← Day5.first_part}"
  IO.println s!"Part 2: {← Day5.second_part}"
  IO.println ""
  IO.println "Day6:"
  IO.println s!"Part 1: {← Day6.part 3}"
  IO.println s!"Part 2: {← Day6.part 13}"
  IO.println ""